### ISSUE TITLE
你好请问 ndkr10 cocos3.14编译出来的app ,报异常 cannot locate symbol "atof" referenced by

### ISSUE THREAD

**Issue by sdfasffsdf** [fusijie/Cocos-Resource#1]
cannot locate symbol "atof" referenced by 请问如何解决呢？求救

**Comment by fusijie** [comment]
没遇到过，你可以试试

[http://www.cnblogs.com/momoshengxiao/p/6784681.html](http://www.cnblogs.com/momoshengxiao/p/6784681.html)

或者到 [@cocos2d-x](https://github.com/cocos2d/cocos2d-x)提问。
